# Generated by Django 3.2.7 on 2021-09-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_idoso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cep',
            field=models.CharField(blank=True, max_length=10, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='account',
            name='cpf',
            field=models.CharField(blank=True, max_length=50, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='account',
            name='numero_res',
            field=models.CharField(blank=True, max_length=6, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='account',
            name='rg',
            field=models.CharField(blank=True, max_length=50, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Sobrenome'),
        ),
    ]
