# Generated by Django 3.2.7 on 2021-10-17 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_auto_20211017_1044'),
        ('servicos', '0002_auto_20211001_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicosolicitado',
            name='idoso_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='cadastro.idoso'),
        ),
        migrations.AlterField(
            model_name='servicosolicitado',
            name='tagservico',
            field=models.CharField(choices=[('', 'Escolha uma Etiqueta'), ('1', 'Serviços da Casa'), ('2', 'Acompanhamento / Carona'), ('3', 'Compras'), ('4', 'Visita'), ('5', 'Diversos')], default='', max_length=15, verbose_name='Etiqueta'),
        ),
    ]
