# Generated by Django 3.2.7 on 2021-10-14 19:06

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('cadastro', '0007_auto_20211001_1802'),
        ('servicos', '0002_auto_20211001_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicosolicitado',
            name='idoso_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='cadastro.idoso'),
        ),
        migrations.RemoveField(
            model_name='servicosolicitado',
            name='tagservico',
        ),
        migrations.AddField(
            model_name='servicosolicitado',
            name='tagservico',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
