# Generated by Django 3.2.7 on 2021-10-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_auto_20211014_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicosolicitado',
            name='tagservico',
        ),
        migrations.AddField(
            model_name='servicosolicitado',
            name='tagservico',
            field=models.CharField(choices=[('', 'Escolha uma Etiqueta'), ('1', 'Serviços da Casa'), ('2', 'Acompanhamento / Carona'), ('3', 'Compras'), ('4', 'Visita'), ('5', 'Diversos')], default='', max_length=15, verbose_name='Etiqueta'),
        ),
    ]
