# Generated by Django 3.2.7 on 2021-10-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_auto_20211017_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicosolicitado',
            name='confirmado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
